### PR TITLE
Remove abuse of ClassMethods and use extend

### PR DESCRIPTION
**Pull request by banister**
as per: http://yehudakatz.com/2009/11/12/better-ruby-idioms/

### CODE REVIEW

**Comment by garybernhardt** [comment]
This is how I wrote it originally, but what if Cls eventually grows instance methods (e.g., initialize as a normal method instead of being evaled)? Or a hash-like `keys` or something? By including instead of extending, we can make that change without breaking backwards compatibility.

(I am open to corrections on that or any arguments that I'm wrong. :)

**Comment by banister** [comment]
In that case, you could use the `extended` hook on the module to bring in an included `InstanceMethods` module.

see: https://gist.github.com/ffed9642dacb28f042bb

**Comment by garybernhardt** [comment]
You're right, of course—it's the same thing either way. I guess I defaulted to include because it's more common, but there's no reason to do that until it's needed. And, conceptually, I think cls is more about changing the class than changing the instances.

**Comment by garybernhardt** [comment]
Updated the README and released as version 0.0.3.

**Pull request merged**
